### ISSUE TITLE
What is your favorite Arnold Schwarzenegger movie?

### ISSUE THREAD

**Issue by mjhenkes** [bjankord/ama#2]
![](https://media.giphy.com/media/LaROsbyapvSV2/giphy.gif)

**Comment by bjankord** [comment]
My favorite Schwarzenegger movie has to be Kindergarten Cop with The Running Man being a close second.
More recently I've enjoyed watching Schwarzenegger's video response to recent events: https://www.youtube.com/watch?v=FN_YIBr0ELM
